### ISSUE TITLE
Tighten up the presentation of definitions

### ISSUE THREAD

**Issue by jakobvase** [leanprover/reference-manual#319]
If you look here: [https://lean-lang.org/doc/reference/latest/find/?domain=Verso.Genre.Manual.doc&name=String.toNat!](https://lean-lang.org/doc/reference/latest/find/?domain=Verso.Genre.Manual.doc&name=String.toNat!), you'll see the definition of `String.toNat!`. It takes up a lot of space for a header and two lines of description. I think we should make it smaller, so it becomes easier to find the definition you're looking for.

Something like this would be nice:

<img width="831" alt="Image" src="https://github.com/user-attachments/assets/026c11f4-19de-4db2-b101-035473a11fa0" />

That's with these css rules applied:

```css
.namedocs .text > :last-child,
.namedocs .text > :last-child * {
    margin-bottom: 0;
}

.namedocs .text > :first-child {
    margin-top: 0;
}
```
